# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-13 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_auto_20171213_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictures',
            old_name='picture',
            new_name='painter',
        ),
        migrations.AddField(
            model_name='pictures',
            name='picture_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
